// AUTO-GENERATED by model/gen_vectors.py -- do not edit by hand.
// Source case: 'multi' (M=16, K=32, N=8, relu=1)
//
// Regenerate with:  python3 model/gen_vectors.py
// CI checks these stay in sync with the model via --check.
localparam int ST_ROWS    = 8;
localparam int ST_COLS    = 8;
localparam int ST_M       = 16;
localparam int ST_PASSES  = 4;
localparam int ST_MULT    = 1271;
localparam int ST_SHIFT   = 20;
localparam int ST_RELU    = 1;
localparam int ST_A_DEPTH = 64;
localparam int ST_W_DEPTH = 32;
localparam int ST_Y_DEPTH = 16;
