// -----------------------------------------------------------------------------
// tile_selftest -- runs a canned matmul on real hardware and checks the result.
//
// The stimulus AND the expected results are the same files the simulation uses,
// generated by model/gen_vectors.py and baked into ROMs here. So the LED on the
// board is asserting exactly the property the testbench asserts: the tile is
// bit-exact with the Python model. A board that lights `pass` has reproduced
// the simulation, not merely "done something".
//
// bp_en drives a pseudo-random y_ready so the stall path gets exercised on
// silicon too -- that is the one thing simulation is least likely to have got
// right, because it depends on the whole array freezing together.
//
// The self-test is entirely self-contained: no bus, no CPU, no external IO
// beyond a start button and a few LEDs, which is what keeps the same module
// usable on two boards with completely different peripherals.
// -----------------------------------------------------------------------------
`default_nettype none

module tile_selftest (
    input  wire        clk,
    input  wire        rst_n,
    input  wire        start,
    input  wire        bp_en,       // exercise backpressure on hardware
    input  wire  [7:0] probe_idx,   // which result byte to expose on probe_data
    output wire        busy,
    output logic       done,
    output logic       pass,
    output logic       fail,
    output wire  [7:0] probe_data
);

`include "selftest_params.svh"

    localparam int ACC_W = 32;
    localparam int YAW   = $clog2(ST_Y_DEPTH);   // result beat index width
    localparam int LAW   = $clog2(ST_COLS);      // lane index width
    localparam int WAW   = $clog2(ST_W_DEPTH);
    localparam int AAW   = $clog2(ST_A_DEPTH);
    localparam int WCW   = $clog2(ST_ROWS + 1);
    localparam int MCW   = $clog2(ST_M + 1);

    // Sized copies of the generated geometry, so the tile's config ports are
    // driven without relying on size casts that older tools reject.
    localparam logic [15:0] CFG_M_LEN = ST_M;
    localparam logic [15:0] CFG_MULT  = ST_MULT;
    localparam logic [5:0]  CFG_SHIFT = ST_SHIFT;

    // -------------------------------------------------------------------------
    // Vectors baked into ROM. Both Quartus and Vivado infer memory from an
    // initial-block $readmemh; the build scripts put the .hex files where the
    // tool looks for them.
    // -------------------------------------------------------------------------
    logic [ST_ROWS*8-1:0]     a_rom    [0:ST_A_DEPTH-1];
    logic [ST_COLS*8-1:0]     w_rom    [0:ST_W_DEPTH-1];
    logic [ST_COLS*8-1:0]     y_rom    [0:ST_Y_DEPTH-1];
    logic [ST_COLS*ACC_W-1:0] bias_rom [0:0];

    initial begin
        $readmemh("selftest_a.hex",    a_rom);
        $readmemh("selftest_w.hex",    w_rom);
        $readmemh("selftest_y.hex",    y_rom);
        $readmemh("selftest_bias.hex", bias_rom);
    end

    // -------------------------------------------------------------------------
    // Sequencer: one start pulse per pass, then weights, then activations.
    // -------------------------------------------------------------------------
    localparam logic [2:0] S_IDLE   = 3'd0;
    localparam logic [2:0] S_START  = 3'd1;
    localparam logic [2:0] S_WEIGHT = 3'd2;
    localparam logic [2:0] S_ACT    = 3'd3;
    localparam logic [2:0] S_WAIT   = 3'd4;
    localparam logic [2:0] S_FINAL  = 3'd5;

    logic [2:0]     state;
    logic [WCW-1:0] pass_idx;
    logic [WCW-1:0] wi;
    logic [MCW-1:0] mi;
    logic [WAW-1:0] w_addr;
    logic [AAW-1:0] a_addr;
    logic           tstart;

    wire              tbusy, tdone;
    wire              w_ready, a_ready;
    wire              y_valid, y_last, tsat;
    wire [ST_COLS*8-1:0] y_data;

    wire w_valid = (state == S_WEIGHT);
    wire a_valid = (state == S_ACT);

    // ROM addresses run flat across all passes, which keeps the read address a
    // plain counter instead of a multiply.
    wire [ST_COLS*8-1:0] w_data = w_rom[w_addr];
    wire [ST_ROWS*8-1:0] a_data = a_rom[a_addr];

    logic [YAW:0] ycnt;
    logic         mismatch;
    wire          clr_results = (state == S_IDLE) && start;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= S_IDLE;
            pass_idx <= '0;
            wi       <= '0;
            mi       <= '0;
            w_addr   <= '0;
            a_addr   <= '0;
            tstart   <= 1'b0;
            done     <= 1'b0;
            pass     <= 1'b0;
            fail     <= 1'b0;
        end else begin
            tstart <= 1'b0;
            case (state)
                S_IDLE: begin
                    if (start) begin
                        pass_idx <= '0;
                        w_addr   <= '0;
                        a_addr   <= '0;
                        done     <= 1'b0;
                        pass     <= 1'b0;
                        fail     <= 1'b0;
                        state    <= S_START;
                    end
                end

                S_START: begin
                    tstart <= 1'b1;
                    wi     <= '0;
                    state  <= S_WEIGHT;
                end

                S_WEIGHT: begin
                    if (w_ready) begin
                        w_addr <= w_addr + 1'b1;
                        if (wi == ST_ROWS - 1) begin
                            mi    <= '0;
                            state <= S_ACT;
                        end else begin
                            wi <= wi + 1'b1;
                        end
                    end
                end

                S_ACT: begin
                    if (a_ready) begin
                        a_addr <= a_addr + 1'b1;
                        if (mi == ST_M - 1) state <= S_WAIT;
                        else                mi    <= mi + 1'b1;
                    end
                end

                S_WAIT: begin
                    if (tdone) begin
                        if (pass_idx == ST_PASSES - 1) begin
                            state <= S_FINAL;
                        end else begin
                            pass_idx <= pass_idx + 1'b1;
                            state    <= S_START;
                        end
                    end
                end

                // The tile can report done while results are still in its output
                // FIFO, so the verdict waits for the stream, not for done.
                S_FINAL: begin
                    if (ycnt == ST_M) begin
                        done  <= 1'b1;
                        pass  <= ~mismatch;
                        fail  <=  mismatch;
                        state <= S_IDLE;
                    end
                end

                default: state <= S_IDLE;
            endcase
        end
    end

    assign busy = (state != S_IDLE);

    // -------------------------------------------------------------------------
    // Result checking and capture
    // -------------------------------------------------------------------------
    logic [ST_COLS*8-1:0] y_cap [0:ST_Y_DEPTH-1];

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            ycnt     <= '0;
            mismatch <= 1'b0;
        end else if (clr_results) begin
            ycnt     <= '0;
            mismatch <= 1'b0;
        end else if (y_valid && y_ready) begin
            if (y_data != y_rom[ycnt[YAW-1:0]]) mismatch <= 1'b1;
            ycnt <= ycnt + 1'b1;
        end
    end

    always_ff @(posedge clk) begin
        if (y_valid && y_ready) y_cap[ycnt[YAW-1:0]] <= y_data;
    end

    wire [ST_COLS*8-1:0] cap_beat = y_cap[probe_idx[LAW +: YAW]];
    assign probe_data = cap_beat[probe_idx[LAW-1:0]*8 +: 8];

    // -------------------------------------------------------------------------
    // Optional hardware backpressure
    // -------------------------------------------------------------------------
    logic [15:0] lfsr;
    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) lfsr <= 16'hACE1;
        else        lfsr <= {lfsr[14:0],
                             lfsr[15] ^ lfsr[13] ^ lfsr[12] ^ lfsr[10]};
    end
    wire y_ready = bp_en ? lfsr[0] : 1'b1;

    // -------------------------------------------------------------------------
    // The tile under test
    // -------------------------------------------------------------------------
    systolic_tile #(
        .ROWS       (ST_ROWS),
        .COLS       (ST_COLS),
        .ACC_W      (ACC_W),
        .MAX_M      (ST_M),
        .FIFO_DEPTH (8)
    ) u_tile (
        .clk        (clk),
        .rst_n      (rst_n),
        .start      (tstart),
        .first_pass (pass_idx == '0),
        .last_pass  (pass_idx == ST_PASSES - 1),
        .cfg_m_len  (CFG_M_LEN),
        .cfg_mult   (CFG_MULT),
        .cfg_shift  (CFG_SHIFT),
        .cfg_relu   (ST_RELU != 0),
        .cfg_bias   (bias_rom[0]),
        .busy       (tbusy),
        .done       (tdone),
        .w_valid    (w_valid),
        .w_ready    (w_ready),
        .w_data     (w_data),
        .a_valid    (a_valid),
        .a_ready    (a_ready),
        .a_data     (a_data),
        .y_valid    (y_valid),
        .y_ready    (y_ready),
        .y_data     (y_data),
        .y_last     (y_last),
        .sat_hit    (tsat)
    );

endmodule

`default_nettype wire
